### ISSUE TITLE
update ticket status counts upon ticket update

### ISSUE THREAD

**Issue by jpalmieri** [zendesk/user_data_app#65]
This is probably an edge case, but thought I should pass it along regardless.

One of our agents noticed that the ticket status totals (the numbers next to the colored letters) don't update when you merge the current ticket. For example, if you open a ticket from a user with two tickets in the "open" state, and then merge that ticket into the other open ticket, the "open" ticket total still shows 2.

**Comment by sostopher** [comment]
This should now be fixed.
